# Generated by Django 3.1.2 on 2020-10-10 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbox', '0002_auto_20201008_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
